# Generated by Django 4.0.3 on 2022-03-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField()),
                ('place', models.TextField()),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('A', 'Sin Especificar'), ('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], default='A', max_length=1, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=150, null=True)),
                ('escolaridad_d', models.CharField(blank=True, max_length=150, null=True)),
                ('name_d', models.CharField(blank=True, max_length=150, null=True)),
                ('ocupacion_d', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='users/denuncia/imagenes')),
                ('video', models.FileField(blank=True, null=True, upload_to='users/denuncia/videos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
