# Generated by Django 4.0.3 on 2022-03-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='imagen',
            field=models.ImageField(null=True, upload_to='users/denuncia/imagenes'),
        ),
        migrations.AlterField(
            model_name='report',
            name='video',
            field=models.FileField(null=True, upload_to='users/denuncia/videos'),
        ),
    ]
